// flow-typed signature: 208d6904e40f65c60f8d34e4873e5af4
// flow-typed version: <<STUB>>/electron-react-devtools_vfirejune/electron-react-devtools/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'electron-react-devtools'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'electron-react-devtools' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'electron-react-devtools/api' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/build/backend' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/build/background' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/build/contentScript' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/build/inject' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/build/main' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/build/panel' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/popups/shared' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/scripts/build' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/scripts/helpers/map' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/scripts/helpers/object-create' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/scripts/helpers/set' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/scripts/helpers/weak-map' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/scripts/webpack.backend' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/scripts/webpack.config' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/agent/__tests__/Agent-test' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/agent/__tests__/dehydrate-test' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/agent/Agent' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/agent/Bridge' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/agent/consts' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/agent/dehydrate' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/agent/getIn' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/agent/hydrate' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/agent/inject' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/backend' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/backend/__tests__/copyWithSet-test' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/backend/attachRenderer' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/backend/attachRendererFiber' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/backend/backend' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/backend/copyWithSet' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/backend/getData' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/backend/getData012' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/backend/getDataFiber' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/backend/getDisplayName' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/backend/installGlobalHook' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/backend/integration/attach-0.11' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/backend/integration/attach-0.12' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/backend/integration/attach-0.13' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/backend/integration/attach-0.14' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/backend/integration/is-travis' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/backend/integration/reporter' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/backend/integration/spy' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/backend/integration/webpack.config' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/backend/ReactTypeOfWork' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/backend/traverseAllChildrenImpl' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/backend/types' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/background' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/checkForReact' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/contentScript' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/flow/chrome' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/flow/performance' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/frontend/BlurInput' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/frontend/Breadcrumb' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/frontend/Container' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/frontend/ContextMenu' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/frontend/DataView/DataView' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/frontend/DataView/previewComplex' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/frontend/DataView/Simple' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/frontend/decorate' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/frontend/detail_pane/DetailPane' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/frontend/detail_pane/DetailPaneSection' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/frontend/dirToDest' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/frontend/Draggable' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/frontend/flash' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/frontend/Highlighter/Highlighter' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/frontend/Highlighter/MultiOverlay' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/frontend/Highlighter/Overlay' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/frontend/Highlighter/setup' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/frontend/HighlightHover' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/frontend/Hoverable' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/frontend/Icons' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/frontend/Input' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/frontend/invariant' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/frontend/keyboardNav' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/frontend/LeftPane' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/frontend/Node' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/frontend/nodeMatchesText' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/frontend/Panel' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/frontend/PreferencesPanel' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/frontend/Props' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/frontend/PropState' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/frontend/PropVal' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/frontend/provideStore' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/frontend/SearchUtils' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/frontend/SettingsCheckbox' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/frontend/SettingsPane' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/frontend/SplitPane' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/frontend/Store' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/frontend/SvgIcon' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/frontend/TabbedPane' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/frontend/Themes/constants' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/frontend/Themes/Editor/ColorGroups' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/frontend/Themes/Editor/ColorInput' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/frontend/Themes/Editor/ColorPicker' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/frontend/Themes/Editor/Editor' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/frontend/Themes/Fonts' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/frontend/Themes/Preview' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/frontend/Themes/Serializer' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/frontend/Themes/Store' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/frontend/Themes/Themes' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/frontend/Themes/utils' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/frontend/TimerSafe' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/frontend/TreeView' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/frontend/types' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/GlobalHook' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/inject' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/main' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/panel' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/plugins/Colorizer/ColorizerFrontendControl' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/plugins/DepGraph/crawlChildren' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/plugins/DepGraph/DepGraph' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/plugins/ReactNativeStyle/AutoSizeInput' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/plugins/ReactNativeStyle/BlurInput' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/plugins/ReactNativeStyle/BoxInspector' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/plugins/ReactNativeStyle/ReactNativeStyle' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/plugins/ReactNativeStyle/resolveBoxStyle' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/plugins/ReactNativeStyle/setupBackend' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/plugins/ReactNativeStyle/StyleEdit' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/plugins/Relay/__tests__/tidyGraphQL-test' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/plugins/Relay/backend' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/plugins/Relay/ElementPanel' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/plugins/Relay/installRelayHook' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/plugins/Relay/QueriesTab' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/plugins/Relay/Query' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/plugins/Relay/QueryList' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/plugins/Relay/QueryViewer' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/plugins/Relay/RelayPlugin' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/plugins/Relay/Store' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/plugins/Relay/StoreTab' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/plugins/Relay/tidyGraphQL' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/plugins/TraceUpdates/TraceUpdatesAbstractNodeMeasurer' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/plugins/TraceUpdates/TraceUpdatesAbstractNodePresenter' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/plugins/TraceUpdates/TraceUpdatesBackendManager' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/plugins/TraceUpdates/TraceUpdatesFrontendControl' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/plugins/TraceUpdates/TraceUpdatesTypes' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/plugins/TraceUpdates/TraceUpdatesWebNodeMeasurer' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/plugins/TraceUpdates/TraceUpdatesWebNodePresenter' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/utils/guid' {
  declare module.exports: any;
}

declare module 'electron-react-devtools/src/utils/serializePropsForCopy' {
  declare module.exports: any;
}

// Filename aliases
declare module 'electron-react-devtools/api.js' {
  declare module.exports: $Exports<'electron-react-devtools/api'>;
}
declare module 'electron-react-devtools/build/backend.js' {
  declare module.exports: $Exports<'electron-react-devtools/build/backend'>;
}
declare module 'electron-react-devtools/build/background.js' {
  declare module.exports: $Exports<'electron-react-devtools/build/background'>;
}
declare module 'electron-react-devtools/build/contentScript.js' {
  declare module.exports: $Exports<'electron-react-devtools/build/contentScript'>;
}
declare module 'electron-react-devtools/build/inject.js' {
  declare module.exports: $Exports<'electron-react-devtools/build/inject'>;
}
declare module 'electron-react-devtools/build/main.js' {
  declare module.exports: $Exports<'electron-react-devtools/build/main'>;
}
declare module 'electron-react-devtools/build/panel.js' {
  declare module.exports: $Exports<'electron-react-devtools/build/panel'>;
}
declare module 'electron-react-devtools/popups/shared.js' {
  declare module.exports: $Exports<'electron-react-devtools/popups/shared'>;
}
declare module 'electron-react-devtools/scripts/build.js' {
  declare module.exports: $Exports<'electron-react-devtools/scripts/build'>;
}
declare module 'electron-react-devtools/scripts/helpers/map.js' {
  declare module.exports: $Exports<'electron-react-devtools/scripts/helpers/map'>;
}
declare module 'electron-react-devtools/scripts/helpers/object-create.js' {
  declare module.exports: $Exports<'electron-react-devtools/scripts/helpers/object-create'>;
}
declare module 'electron-react-devtools/scripts/helpers/set.js' {
  declare module.exports: $Exports<'electron-react-devtools/scripts/helpers/set'>;
}
declare module 'electron-react-devtools/scripts/helpers/weak-map.js' {
  declare module.exports: $Exports<'electron-react-devtools/scripts/helpers/weak-map'>;
}
declare module 'electron-react-devtools/scripts/webpack.backend.js' {
  declare module.exports: $Exports<'electron-react-devtools/scripts/webpack.backend'>;
}
declare module 'electron-react-devtools/scripts/webpack.config.js' {
  declare module.exports: $Exports<'electron-react-devtools/scripts/webpack.config'>;
}
declare module 'electron-react-devtools/src/agent/__tests__/Agent-test.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/agent/__tests__/Agent-test'>;
}
declare module 'electron-react-devtools/src/agent/__tests__/dehydrate-test.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/agent/__tests__/dehydrate-test'>;
}
declare module 'electron-react-devtools/src/agent/Agent.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/agent/Agent'>;
}
declare module 'electron-react-devtools/src/agent/Bridge.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/agent/Bridge'>;
}
declare module 'electron-react-devtools/src/agent/consts.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/agent/consts'>;
}
declare module 'electron-react-devtools/src/agent/dehydrate.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/agent/dehydrate'>;
}
declare module 'electron-react-devtools/src/agent/getIn.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/agent/getIn'>;
}
declare module 'electron-react-devtools/src/agent/hydrate.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/agent/hydrate'>;
}
declare module 'electron-react-devtools/src/agent/inject.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/agent/inject'>;
}
declare module 'electron-react-devtools/src/backend.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/backend'>;
}
declare module 'electron-react-devtools/src/backend/__tests__/copyWithSet-test.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/backend/__tests__/copyWithSet-test'>;
}
declare module 'electron-react-devtools/src/backend/attachRenderer.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/backend/attachRenderer'>;
}
declare module 'electron-react-devtools/src/backend/attachRendererFiber.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/backend/attachRendererFiber'>;
}
declare module 'electron-react-devtools/src/backend/backend.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/backend/backend'>;
}
declare module 'electron-react-devtools/src/backend/copyWithSet.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/backend/copyWithSet'>;
}
declare module 'electron-react-devtools/src/backend/getData.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/backend/getData'>;
}
declare module 'electron-react-devtools/src/backend/getData012.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/backend/getData012'>;
}
declare module 'electron-react-devtools/src/backend/getDataFiber.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/backend/getDataFiber'>;
}
declare module 'electron-react-devtools/src/backend/getDisplayName.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/backend/getDisplayName'>;
}
declare module 'electron-react-devtools/src/backend/installGlobalHook.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/backend/installGlobalHook'>;
}
declare module 'electron-react-devtools/src/backend/integration/attach-0.11.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/backend/integration/attach-0.11'>;
}
declare module 'electron-react-devtools/src/backend/integration/attach-0.12.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/backend/integration/attach-0.12'>;
}
declare module 'electron-react-devtools/src/backend/integration/attach-0.13.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/backend/integration/attach-0.13'>;
}
declare module 'electron-react-devtools/src/backend/integration/attach-0.14.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/backend/integration/attach-0.14'>;
}
declare module 'electron-react-devtools/src/backend/integration/is-travis.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/backend/integration/is-travis'>;
}
declare module 'electron-react-devtools/src/backend/integration/reporter.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/backend/integration/reporter'>;
}
declare module 'electron-react-devtools/src/backend/integration/spy.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/backend/integration/spy'>;
}
declare module 'electron-react-devtools/src/backend/integration/webpack.config.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/backend/integration/webpack.config'>;
}
declare module 'electron-react-devtools/src/backend/ReactTypeOfWork.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/backend/ReactTypeOfWork'>;
}
declare module 'electron-react-devtools/src/backend/traverseAllChildrenImpl.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/backend/traverseAllChildrenImpl'>;
}
declare module 'electron-react-devtools/src/backend/types.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/backend/types'>;
}
declare module 'electron-react-devtools/src/background.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/background'>;
}
declare module 'electron-react-devtools/src/checkForReact.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/checkForReact'>;
}
declare module 'electron-react-devtools/src/contentScript.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/contentScript'>;
}
declare module 'electron-react-devtools/src/flow/chrome.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/flow/chrome'>;
}
declare module 'electron-react-devtools/src/flow/performance.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/flow/performance'>;
}
declare module 'electron-react-devtools/src/frontend/BlurInput.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/frontend/BlurInput'>;
}
declare module 'electron-react-devtools/src/frontend/Breadcrumb.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/frontend/Breadcrumb'>;
}
declare module 'electron-react-devtools/src/frontend/Container.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/frontend/Container'>;
}
declare module 'electron-react-devtools/src/frontend/ContextMenu.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/frontend/ContextMenu'>;
}
declare module 'electron-react-devtools/src/frontend/DataView/DataView.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/frontend/DataView/DataView'>;
}
declare module 'electron-react-devtools/src/frontend/DataView/previewComplex.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/frontend/DataView/previewComplex'>;
}
declare module 'electron-react-devtools/src/frontend/DataView/Simple.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/frontend/DataView/Simple'>;
}
declare module 'electron-react-devtools/src/frontend/decorate.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/frontend/decorate'>;
}
declare module 'electron-react-devtools/src/frontend/detail_pane/DetailPane.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/frontend/detail_pane/DetailPane'>;
}
declare module 'electron-react-devtools/src/frontend/detail_pane/DetailPaneSection.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/frontend/detail_pane/DetailPaneSection'>;
}
declare module 'electron-react-devtools/src/frontend/dirToDest.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/frontend/dirToDest'>;
}
declare module 'electron-react-devtools/src/frontend/Draggable.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/frontend/Draggable'>;
}
declare module 'electron-react-devtools/src/frontend/flash.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/frontend/flash'>;
}
declare module 'electron-react-devtools/src/frontend/Highlighter/Highlighter.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/frontend/Highlighter/Highlighter'>;
}
declare module 'electron-react-devtools/src/frontend/Highlighter/MultiOverlay.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/frontend/Highlighter/MultiOverlay'>;
}
declare module 'electron-react-devtools/src/frontend/Highlighter/Overlay.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/frontend/Highlighter/Overlay'>;
}
declare module 'electron-react-devtools/src/frontend/Highlighter/setup.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/frontend/Highlighter/setup'>;
}
declare module 'electron-react-devtools/src/frontend/HighlightHover.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/frontend/HighlightHover'>;
}
declare module 'electron-react-devtools/src/frontend/Hoverable.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/frontend/Hoverable'>;
}
declare module 'electron-react-devtools/src/frontend/Icons.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/frontend/Icons'>;
}
declare module 'electron-react-devtools/src/frontend/Input.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/frontend/Input'>;
}
declare module 'electron-react-devtools/src/frontend/invariant.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/frontend/invariant'>;
}
declare module 'electron-react-devtools/src/frontend/keyboardNav.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/frontend/keyboardNav'>;
}
declare module 'electron-react-devtools/src/frontend/LeftPane.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/frontend/LeftPane'>;
}
declare module 'electron-react-devtools/src/frontend/Node.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/frontend/Node'>;
}
declare module 'electron-react-devtools/src/frontend/nodeMatchesText.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/frontend/nodeMatchesText'>;
}
declare module 'electron-react-devtools/src/frontend/Panel.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/frontend/Panel'>;
}
declare module 'electron-react-devtools/src/frontend/PreferencesPanel.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/frontend/PreferencesPanel'>;
}
declare module 'electron-react-devtools/src/frontend/Props.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/frontend/Props'>;
}
declare module 'electron-react-devtools/src/frontend/PropState.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/frontend/PropState'>;
}
declare module 'electron-react-devtools/src/frontend/PropVal.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/frontend/PropVal'>;
}
declare module 'electron-react-devtools/src/frontend/provideStore.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/frontend/provideStore'>;
}
declare module 'electron-react-devtools/src/frontend/SearchUtils.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/frontend/SearchUtils'>;
}
declare module 'electron-react-devtools/src/frontend/SettingsCheckbox.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/frontend/SettingsCheckbox'>;
}
declare module 'electron-react-devtools/src/frontend/SettingsPane.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/frontend/SettingsPane'>;
}
declare module 'electron-react-devtools/src/frontend/SplitPane.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/frontend/SplitPane'>;
}
declare module 'electron-react-devtools/src/frontend/Store.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/frontend/Store'>;
}
declare module 'electron-react-devtools/src/frontend/SvgIcon.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/frontend/SvgIcon'>;
}
declare module 'electron-react-devtools/src/frontend/TabbedPane.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/frontend/TabbedPane'>;
}
declare module 'electron-react-devtools/src/frontend/Themes/constants.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/frontend/Themes/constants'>;
}
declare module 'electron-react-devtools/src/frontend/Themes/Editor/ColorGroups.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/frontend/Themes/Editor/ColorGroups'>;
}
declare module 'electron-react-devtools/src/frontend/Themes/Editor/ColorInput.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/frontend/Themes/Editor/ColorInput'>;
}
declare module 'electron-react-devtools/src/frontend/Themes/Editor/ColorPicker.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/frontend/Themes/Editor/ColorPicker'>;
}
declare module 'electron-react-devtools/src/frontend/Themes/Editor/Editor.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/frontend/Themes/Editor/Editor'>;
}
declare module 'electron-react-devtools/src/frontend/Themes/Fonts.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/frontend/Themes/Fonts'>;
}
declare module 'electron-react-devtools/src/frontend/Themes/Preview.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/frontend/Themes/Preview'>;
}
declare module 'electron-react-devtools/src/frontend/Themes/Serializer.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/frontend/Themes/Serializer'>;
}
declare module 'electron-react-devtools/src/frontend/Themes/Store.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/frontend/Themes/Store'>;
}
declare module 'electron-react-devtools/src/frontend/Themes/Themes.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/frontend/Themes/Themes'>;
}
declare module 'electron-react-devtools/src/frontend/Themes/utils.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/frontend/Themes/utils'>;
}
declare module 'electron-react-devtools/src/frontend/TimerSafe.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/frontend/TimerSafe'>;
}
declare module 'electron-react-devtools/src/frontend/TreeView.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/frontend/TreeView'>;
}
declare module 'electron-react-devtools/src/frontend/types.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/frontend/types'>;
}
declare module 'electron-react-devtools/src/GlobalHook.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/GlobalHook'>;
}
declare module 'electron-react-devtools/src/inject.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/inject'>;
}
declare module 'electron-react-devtools/src/main.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/main'>;
}
declare module 'electron-react-devtools/src/panel.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/panel'>;
}
declare module 'electron-react-devtools/src/plugins/Colorizer/ColorizerFrontendControl.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/plugins/Colorizer/ColorizerFrontendControl'>;
}
declare module 'electron-react-devtools/src/plugins/DepGraph/crawlChildren.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/plugins/DepGraph/crawlChildren'>;
}
declare module 'electron-react-devtools/src/plugins/DepGraph/DepGraph.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/plugins/DepGraph/DepGraph'>;
}
declare module 'electron-react-devtools/src/plugins/ReactNativeStyle/AutoSizeInput.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/plugins/ReactNativeStyle/AutoSizeInput'>;
}
declare module 'electron-react-devtools/src/plugins/ReactNativeStyle/BlurInput.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/plugins/ReactNativeStyle/BlurInput'>;
}
declare module 'electron-react-devtools/src/plugins/ReactNativeStyle/BoxInspector.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/plugins/ReactNativeStyle/BoxInspector'>;
}
declare module 'electron-react-devtools/src/plugins/ReactNativeStyle/ReactNativeStyle.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/plugins/ReactNativeStyle/ReactNativeStyle'>;
}
declare module 'electron-react-devtools/src/plugins/ReactNativeStyle/resolveBoxStyle.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/plugins/ReactNativeStyle/resolveBoxStyle'>;
}
declare module 'electron-react-devtools/src/plugins/ReactNativeStyle/setupBackend.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/plugins/ReactNativeStyle/setupBackend'>;
}
declare module 'electron-react-devtools/src/plugins/ReactNativeStyle/StyleEdit.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/plugins/ReactNativeStyle/StyleEdit'>;
}
declare module 'electron-react-devtools/src/plugins/Relay/__tests__/tidyGraphQL-test.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/plugins/Relay/__tests__/tidyGraphQL-test'>;
}
declare module 'electron-react-devtools/src/plugins/Relay/backend.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/plugins/Relay/backend'>;
}
declare module 'electron-react-devtools/src/plugins/Relay/ElementPanel.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/plugins/Relay/ElementPanel'>;
}
declare module 'electron-react-devtools/src/plugins/Relay/installRelayHook.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/plugins/Relay/installRelayHook'>;
}
declare module 'electron-react-devtools/src/plugins/Relay/QueriesTab.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/plugins/Relay/QueriesTab'>;
}
declare module 'electron-react-devtools/src/plugins/Relay/Query.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/plugins/Relay/Query'>;
}
declare module 'electron-react-devtools/src/plugins/Relay/QueryList.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/plugins/Relay/QueryList'>;
}
declare module 'electron-react-devtools/src/plugins/Relay/QueryViewer.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/plugins/Relay/QueryViewer'>;
}
declare module 'electron-react-devtools/src/plugins/Relay/RelayPlugin.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/plugins/Relay/RelayPlugin'>;
}
declare module 'electron-react-devtools/src/plugins/Relay/Store.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/plugins/Relay/Store'>;
}
declare module 'electron-react-devtools/src/plugins/Relay/StoreTab.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/plugins/Relay/StoreTab'>;
}
declare module 'electron-react-devtools/src/plugins/Relay/tidyGraphQL.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/plugins/Relay/tidyGraphQL'>;
}
declare module 'electron-react-devtools/src/plugins/TraceUpdates/TraceUpdatesAbstractNodeMeasurer.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/plugins/TraceUpdates/TraceUpdatesAbstractNodeMeasurer'>;
}
declare module 'electron-react-devtools/src/plugins/TraceUpdates/TraceUpdatesAbstractNodePresenter.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/plugins/TraceUpdates/TraceUpdatesAbstractNodePresenter'>;
}
declare module 'electron-react-devtools/src/plugins/TraceUpdates/TraceUpdatesBackendManager.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/plugins/TraceUpdates/TraceUpdatesBackendManager'>;
}
declare module 'electron-react-devtools/src/plugins/TraceUpdates/TraceUpdatesFrontendControl.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/plugins/TraceUpdates/TraceUpdatesFrontendControl'>;
}
declare module 'electron-react-devtools/src/plugins/TraceUpdates/TraceUpdatesTypes.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/plugins/TraceUpdates/TraceUpdatesTypes'>;
}
declare module 'electron-react-devtools/src/plugins/TraceUpdates/TraceUpdatesWebNodeMeasurer.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/plugins/TraceUpdates/TraceUpdatesWebNodeMeasurer'>;
}
declare module 'electron-react-devtools/src/plugins/TraceUpdates/TraceUpdatesWebNodePresenter.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/plugins/TraceUpdates/TraceUpdatesWebNodePresenter'>;
}
declare module 'electron-react-devtools/src/utils/guid.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/utils/guid'>;
}
declare module 'electron-react-devtools/src/utils/serializePropsForCopy.js' {
  declare module.exports: $Exports<'electron-react-devtools/src/utils/serializePropsForCopy'>;
}
