// flow-typed signature: d3522bf417b3ba20dfc53fd340310c8e
// flow-typed version: <<STUB>>/redux-persist-electron-storage_v^1.1.2/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-persist-electron-storage'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-persist-electron-storage' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-persist-electron-storage/lib/index' {
  declare module.exports: any;
}

declare module 'redux-persist-electron-storage/src/index' {
  declare module.exports: any;
}

declare module 'redux-persist-electron-storage/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-persist-electron-storage/lib/index.js' {
  declare module.exports: $Exports<'redux-persist-electron-storage/lib/index'>;
}
declare module 'redux-persist-electron-storage/src/index.js' {
  declare module.exports: $Exports<'redux-persist-electron-storage/src/index'>;
}
declare module 'redux-persist-electron-storage/test/test.js' {
  declare module.exports: $Exports<'redux-persist-electron-storage/test/test'>;
}
